#+title: Youtube Dowwnload script that will automatically orginize your downloads into a folder structure according to Video and Music Genres, Music Artist, Music Video types (Concerts, Live...) etc.


* Description
:PROPERTIES:
:ID:       280135a0-2cff-4e93-8679-7d1a6d56b7b2
:END:


After many years of using ytdl I managed to come up with this simple script that will perfectly orginize all of my downloads into a desired folder structure. This is an alternative to software like youtube archivist, tubesync and the latest one I started using ytdl-sub which provides much more advanced usage of yt-dlp, but for noobs or just a simple download of youtube content this script is perfect. Enjoy!



* Dependencies
:PROPERTIES:
:ID:       01577a0a-852e-481a-b9b3-791b68594f96
:END:
Before installing, make sure you have yt-dlp:
https://github.com/yt-dlp/yt-dlp




* To run
:PROPERTIES:
:ID:       a0417c61-3fd8-40a0-9385-6c5aaed37337
:END:

#+begin_src bash

$ git clone https://github.com/RogueGhost93/Youtube
$ cd Youtube
$ chmod +x ytdl.sh
#+end_src



* Usage
:PROPERTIES:
:ID:       9e995141-b386-4962-9842-7209bedc5651
:END:
==========================================================================================================================================================
Option:  "music" will download only audio of the entire music playlist as Origin/Genre/Artist/Folder-like-'Concerts' if applied/songs.ext
Usage:   music 'Origin Strano|Domace' 'Genre' 'Artist' 'Link' 'Extra folder if desired e.g. Concerts/Live'
Example: music 'Foreign' 'Oldies' 'Roy Orbinson' 'https://www.youtube.com/playlist?list=PLvPrczMM8gz3y1Iboy6CsZ432HjCWUQgR' 'Concerts'
==========================================================================================================================================================
Option:  "music_videos" will download the entire music playlist as Origin/Genre/Artist/Folder-like-'Concerts' if applied/songs.ext
Usage:   music_videos 'Origin Strano|Domace' 'Genre' 'Artist' 'Link' 'Extra folder if desired e.g. Concerts/Live'
Example: music_videos 'Domestic' 'Yugoslavia' 'Djordje Balasevic' 'https://www.youtube.com/watch?v=z62StmSvXgo' 'Live'
==========================================================================================================================================================
Option:   "archive" will download the entire channel with the --match-filters applied. Organized as Genre/Channel/Playlist Name/videoname.ext
Usage:    archive 'GENRE' 'LINK'
Example:  archive 'Networking' 'https://www.youtube.com/@homenetworkguy/playlists'
==========================================================================================================================================================
Option:  "documentary_single" will download a single documentary regardless if it belongs to a playlist or not; in form /Title/title.ext with an option to
         override the folder title name with the 3rd argument like in example below to become /Overriden title/title.ext
Usage:   documentary_single 'Genre' 'Link' 'Override Title'
Example: documentary_single 'Economics' 'https://www.youtube.com/watch?v=wdJFeSY8UVk' 'Best documentary ever'
==========================================================================================================================================================
Option:  "documentary_playlist" will download the entire documentary playlist in form '/playlist-name/S(Year)-E(Playlist-index) - title.ext' with an option to
         override the playlist name with the 3rd argument like in example below to become '/overriden-playlist-name/S(Year)-E(Playlist-index) - title.ext'
Usage:   documentary_playlist 'Genre' 'Link' 'Override Playlist Name'
Example: documentary_playlist 'Economics' 'https://www.youtube.com/watch?v=DyV0OfU3-FU&list=PLE88E9ICdiphYjJkeeLL2O09eJoC8r7Dc' 'Hidden Secrets of Money'
==========================================================================================================================================================



#+begin_src
# Open ytdl.sh in order to define your channels you would like to download.
# You can also change any variable in ytdl.sh file such as download or config location.
$ cd /home/$USER/Youtube
$ ./ytdl.sh
#+end_src
